transactions = 4

traceback_limit = 4

#db logging echo(False, True) default: False
db_echo=false

#v2b max replay exchange count(state = faild)
v2b_maxtimes = 99

[btc_conn]
    user = "btc"
    password = "btc"
    host = "127.0.0.1"
    port = 8066
    domain = "violaslayer"
    server = "violaslayer"

[[violas_nodes]]
    host = "52.27.228.84"
    port = 50001
    name = "violas 1"

[[violas_nodes]]
    host = "13.68.141.242"
    port = 50001
    name = "violas 2"

[[violas_nodes]]
    host = "47.52.195.50"
    port = 50001
    name = "violas 3"

[[violas_nodes]]
    host = "18.220.66.235"
    port = 50001
    name = "violas 4"

[[libra_nodes]]
    host = "http://client.testnet.libra.org"
    name = "libra"

[[violas_servers]]
    host = "52.27.228.84"
    port = 4000
    user = "violas"
    password = "violas"

[[db_list]]
    host = "127.0.0.1"
    port = 6378
    db = "lfilter"
    password = "violas"
    step = 500

[[db_list]]
    host = "127.0.0.1"
    port = 6378
    db = "vfilter"
    password = "violas"
    step = 500

[[db_list]]
    host = "127.0.0.1"
    port = 6378
    db = "bfilter"
    password = "violas"
    step = 500

[[db_list]]
    host = "127.0.0.1"
    port = 6378
    db = "v2b"
    password = "violas"
    step = 500

[[db_list]]
    host = "127.0.0.1"
    port = 6378
    db = "l2v"
    password = "violas"
    step = 500

[[db_list]]
    host = "127.0.0.1"
    port = 6378
    db = "v2l"
    password = "1"
    step = 500

[[db_list]]
    host = "127.0.0.1"
    port = 6378
    db = "b2v"
    password = "1"
    step = 500

[[db_list]]
    host = "127.0.0.1"
    port = 6378
    db = "b2v"
    password = "1"
    step = 500

[[db_list]]
    host = "127.0.0.1"
    port = 6378
    db = "record"
    password = "1"
    step = 500

[address_list]
    [[address_list.receiver]]
        address = "dcfa787ecb304c20ff24ed6b5519c2e5cae5f8464c564aabb684ecbcc19153e9"
        type = "v2b"
        chain = "violas"

    [[address_list.receiver]]
        address = "5f4d3d86949fafc804d6c457d9a92bf9ee1e24e8fc664894709c947b74823b2f"
        type = "v2l"
        chain = "violas"
    
    [[address_list.receiver]]
        address = "c16af35c8082f78399bedabfd1ec8c409334bb5e39e5919e081b6db72482e139"
        type = "l2v"
        chain = "libra"
        network = "ex"

    [[address_list.receiver]]
        address = "2MyMHV6e4wA2ucV8fFKzXSEFCwrUGr2HEmY"
        type = "b2v"
        chain = "btc"
    
    [[address_list.sender]]
        address = "270be97cae6bf9ecca084dfa6c7117badabe5de7fa81c906a5a23d5267138aa9"
        type = "b2v"
        chain = "violas"

    [[address_list.sender]]
        address = "2MwBFJJn1f5Sg242D3wNUinKUCKS3GzCn7j"
        type = "v2b"
        chain = "btc"

    [[address_list.sender]]
        address = "2MyMHV6e4wA2ucV8fFKzXSEFCwrUGr2HEmY"
        type = "v2b"
        chain = "btc"

    [[address_list.sender]]
        address = "2N9fQcit5KB8vJHmBF5Z4DkUUTCgJA8GKb3"
        type = "v2b"
        chain = "btc"

    [[address_list.sender]]
        address = "7d572ec38dd124ad4faec3fc077217efab88cc9dd86f72d8816b3cabf155eb86"
        type = "v2l"
        chain = "libra"

    [[address_list.sender]]
        address = "7b102beb21460be85948a41bd2080265149bf4deff39f896c836a2760f6806b9"
        type = "l2v"
        chain = "violas"

    [[address_list.module]]
        address = "00000000000000000000000000000000e1be1ab8360a35a0259f1c93e3eac736"
        type = "v2b"
        chain = "violas"

    [[address_list.module]]
        address = "00000000000000000000000000000000e1be1ab8360a35a0259f1c93e3eac736"
        type = "b2v"
        chain = "btc"

    [[address_list.module]]
        address = "00000000000000000000000000000000e1be1ab8360a35a0259f1c93e3eac736"
        type = "b2v"
        chain = "violas"

    [[address_list.module]]
        address = "00000000000000000000000000000000e1be1ab8360a35a0259f1c93e3eac736"
        type = "v2l"
        chain = "violas"

    [[address_list.module]]
        address = "0000000000000000000000000000000000000000000000000000000000000000"
        type = "v2l"
        chain = "libra"

    [[address_list.module]]
        address = "0000000000000000000000000000000000000000000000000000000000000000"
        type = "l2v"
        chain = "libra"

    [[address_list.module]]
        address = "00000000000000000000000000000000e1be1ab8360a35a0259f1c93e3eac736"
        type = "l2v"
        chain = "violas"

    [[address_list.token]]
        address = "03d3bbb134e5d31b194d910e2d94e37ca0dd2abf254d09de85d49290250a8190"
        tokenid = 5
        tokenname = "vbtc"
        type = "v2b"
        chain = "violas"

    [[address_list.token]]
        address = "03d3bbb134e5d31b194d910e2d94e37ca0dd2abf254d09de85d49290250a8190"
        tokenid = 5
        tokenname = "vbtc"
        type = ""
        chain = "violas"

    [[address_list.token]]
        address = "1eaa12e8c4f196c24ed88ac5f472f128c7ef87304c0b9e477f17dcfd69abd0bb"
        tokenid = 6
        tokenname = "vlibra"
        type = "v2l"
        chain = "violas"

    [[address_list.token]]
        address = "1eaa12e8c4f196c24ed88ac5f472f128c7ef87304c0b9e477f17dcfd69abd0bb"
        tokenid = 6
        tokenname = "vlibra"
        type = "l2v"
        chain = "violas"

    [[address_list.combine]]
        address = "b93bb580bfba22c6d06ba5baac329b0c23e5d616f55614100b83ddece7a4c005"
        type = "v2b"
        chain = "violas"

    [[address_list.combine]]
        address = "4a5a4d3fa63633fbecfd50a17b4b5a38dfbac8a5a08be9e4b958b4aeb9e8f0ea"
        type = "v2l"
        chain = "violas"

    [[address_list.combine]]
        address = "ed997d48192d313deda1d0335722a9bf231bded0afc5ff71c3882b4865cc2f0b"
        type = "l2v"
        chain = "libra"

    [[address_list.combine]]
        address = "2N9fQcit5KB8vJHmBF5Z4DkUUTCgJA8GKb3"
        type = "b2v"
        chain = "btc"
[looping_sleep]
    v2b = 1
    b2v = 1
    v2l = 1
    l2v = 1
    vfilter = 1
    lfilter = 1
    v2bproof = 1
    v2lproof 1
    comm = 8
