transactions = 4

traceback_limit = 4

#db logging echo(False, True) default: False
db_echo=false

#v2b max replay exchange count(state = faild)
v2b_maxtimes = 99

[btc_conn]
    user = "btc"
    password = "btc"
    host = "127.0.0.1"
    port = 8066
    domain = "violaslayer"
    server = "violaslayer"

[[violas_nodes]]
    host = "52.27.228.84"
    port = 50001
    name = "violas 1"
    faucet = "mint_test.key"

[[violas_nodes]]
    host = "13.68.141.242"
    port = 50001
    name = "violas 2"
    faucet = "mint_test.key"

[[violas_nodes]]
    host = "47.52.195.50"
    port = 50001
    name = "violas 3"
    faucet = "mint_test.key"

[[violas_nodes]]
    host = "18.220.66.235"
    port = 50001
    name = "violas 4"
    faucet = "mint_test.key"

[[libra_nodes]]
    host = "http://client.testnet.libra.org"
    name = "libra"

[[violas_servers]]
    host = "52.27.228.84"
    port = 4000
    user = "violas"
    password = "violas"

[[db_list]]
    host = "127.0.0.1"
    port = 6378
    db = "lfilter"
    password = "violas"
    step = 500

[[db_list]]
    host = "127.0.0.1"
    port = 6378
    db = "vfilter"
    password = "violas"
    step = 500

[[db_list]]
    host = "127.0.0.1"
    port = 6378
    db = "bfilter"
    password = "violas"
    step = 500

[[db_list]]
    host = "127.0.0.1"
    port = 6378
    db = "v2b"
    password = "violas"
    step = 500

[[db_list]]
    host = "127.0.0.1"
    port = 6378
    db = "l2v"
    password = "violas"
    step = 500

[[db_list]]
    host = "127.0.0.1"
    port = 6378
    db = "v2l"
    password = "violas"
    step = 500

[[db_list]]
    host = "127.0.0.1"
    port = 6378
    db = "b2v"
    password = "violas"
    step = 500

[[db_list]]
    host = "127.0.0.1"
    port = 6378
    db = "b2v"
    password = "violas"
    step = 500

[[db_list]]
    host = "127.0.0.1"
    port = 6378
    db = "record"
    password = "violas"
    step = 500

#violas <-> libra token map
[token_map]
    [token_map.v2l]
        LBRUSD = "USD"
        LBREUR = "EUR"
        LBRSGD = "SGD"
        LBRGBT = "GBT"
        VLSUSD = "LBRUSD"
        VLSEUR = "LBREUR"
        VLSSGD = "LBRSGD"
        VLSGBT = "LBRGBT"
    [token_map.l2v]
        USD = "LBRUSD"
        EUR = "LBREUR"
        SGD = "LBRSGD"
        GBT = "LBRGBT"
    [token_map.v2b]
        BTCBTC = "BTC"
    [token_map.b2v]
        BTC = "BTCBTC"

#opt type map target token
[type_token_map]
    v2b = "BTC"
    b2v = "BTCBTC"
    v2lusd = "Usd"
    v2leur = "Eur"
    v2lsgd = "Sgd"
    v2lgbt = "gbt"
    l2vusd = "VLSUSD"
    l2veur = "VLSEUR"
    l2vSGD = "VLSSGD"
    l2vgbt = "VLSGBT"

[address_list]
    #receiver addresses
    ##violas chain receiver address
    [[address_list.receiver]]
        address = "4f93ec275410e8be891ff0fd5da41c43aee27591e222fb466654b4f983d8adbb"
        type = "v2b"
        chain = "violas"

    [[address_list.receiver]]
        address = "7cd40d7664d5523d360e8a1e0e2682a2dc49a7c8979f83cde4bc229fb35fd27f"
        type = "v2lusd"
        chain = "violas"
    
    [[address_list.receiver]]
        address = "7cd40d7664d5523d360e8a1e0e2682a2dc49a7c8979f83cde4bc229fb35fd27f"
        type = "v2leur"
        chain = "violas"

    [[address_list.receiver]]
        address = "7cd40d7664d5523d360e8a1e0e2682a2dc49a7c8979f83cde4bc229fb35fd27f"
        type = "v2lgbt"
        chain = "violas"

    [[address_list.receiver]]
        address = "7cd40d7664d5523d360e8a1e0e2682a2dc49a7c8979f83cde4bc229fb35fd27f"
        type = "v2lsgd"
        chain = "violas"

    ##btc chain receiver address
    [[address_list.receiver]]
        address = "2MyMHV6e4wA2ucV8fFKzXSEFCwrUGr2HEmY"
        type = "b2v"
        chain = "btc"
    
    ##libra chain receiver address
    [[address_list.receiver]]
        address = "a239632a99a92e38eeade27b5e3023e22ab774f228b719991463adf0515688a9"
        type = "l2vusd"
        chain = "libra"

    [[address_list.receiver]]
        address = ""
        type = "l2veur"
        chain = "libra"

    [[address_list.receiver]]
        address = "a239632a99a92e38eeade27b5e3023e22ab774f228b719991463adf0515688a9"
        type = "l2vgbt"
        chain = "libra"

    [[address_list.receiver]]
        address = "a239632a99a92e38eeade27b5e3023e22ab774f228b719991463adf0515688a9"
        type = "l2vsgd"
        chain = "libra"

    #sender address
    [[address_list.sender]]
        address = "4f93ec275410e8be891ff0fd5da41c43aee27591e222fb466654b4f983d8adbb"
        type = "b2v"
        chain = "violas"

    [[address_list.sender]]
        address = "2MwBFJJn1f5Sg242D3wNUinKUCKS3GzCn7j"
        type = "v2b"
        chain = "btc"

    [[address_list.sender]]
        address = "2MyMHV6e4wA2ucV8fFKzXSEFCwrUGr2HEmY"
        type = "v2b"
        chain = "btc"

    [[address_list.sender]]
        address = "2N9fQcit5KB8vJHmBF5Z4DkUUTCgJA8GKb3"
        type = "v2b"
        chain = "btc"

    [[address_list.sender]]
        address = "7cd40d7664d5523d360e8a1e0e2682a2dc49a7c8979f83cde4bc229fb35fd27f"
        type = "v2lusd"
        chain = "libra"

    [[address_list.sender]]
        address = "7cd40d7664d5523d360e8a1e0e2682a2dc49a7c8979f83cde4bc229fb35fd27f"
        type = "v2leur"
        chain = "libra"

    [[address_list.sender]]
        address = "7cd40d7664d5523d360e8a1e0e2682a2dc49a7c8979f83cde4bc229fb35fd27f"
        type = "v2lgbt"
        chain = "libra"

    [[address_list.sender]]
        address = "7cd40d7664d5523d360e8a1e0e2682a2dc49a7c8979f83cde4bc229fb35fd27f"
        type = "v2lsgd"
        chain = "libra"

    #currency code
    [[address_list.module]]
        address = "0000000000000000000000000000000000000000000000000000000000000000"
        type = "v2b"
        chain = "violas"

    [[address_list.module]]
        address = "0000000000000000000000000000000000000000000000000000000000000000"
        type = "b2v"
        chain = "btc"

    [[address_list.module]]
        address = "0000000000000000000000000000000000000000000000000000000000000000"
        type = "b2v"
        chain = "violas"

    [[address_list.module]]
        address = "0000000000000000000000000000000000000000000000000000000000000000"
        type = "v2lusd"
        chain = "violas"

    [[address_list.module]]
        address = "0000000000000000000000000000000000000000000000000000000000000000"
        type = "v2leur"
        chain = "libra"

    [[address_list.module]]
        address = "0000000000000000000000000000000000000000000000000000000000000000"
        type = "l2vsgd"
        chain = "libra"

    [[address_list.module]]
        address = "0000000000000000000000000000000000000000000000000000000000000000"
        type = "l2vgbt"
        chain = "violas"

    #token info
    [[address_list.token]]
        address = "0000000000000000000000000000000000000000000000000000000000000000"
        tokenid = "BTCBTC"
        tokenname = "BTCBTC"
        type = "v2b"
        chain = "violas"

    [[address_list.token]]
        address = "0000000000000000000000000000000000000000000000000000000000000000"
        tokenid = "LBRUSD"
        tokenname = "LBRUSD"
        type = "v2lusd"
        chain = "violas"

    [[address_list.token]]
        address = "0000000000000000000000000000000000000000000000000000000000000000"
        tokenid = "LBREUR"
        tokenname = "LBREUR"
        type = "v2leur"
        chain = "violas"

    [[address_list.token]]
        address = "0000000000000000000000000000000000000000000000000000000000000000"
        tokenid = "LBRSGD"
        tokenname = "LBRSGD"
        type = "v2lSGD"
        chain = "violas"

    [[address_list.token]]
        address = "0000000000000000000000000000000000000000000000000000000000000000"
        tokenid = "LBRGBT"
        tokenname = "LBRGBT"
        type = "v2lgbt"
        chain = "violas"

    [[address_list.combine]]
        address = "2N9fQcit5KB8vJHmBF5Z4DkUUTCgJA8GKb3"
        type = "b2v"
        chain = "btc"
[looping_sleep]
    v2b = 1
    b2v = 1
    v2l = 1
    l2v = 1
    vfilter = 1
    lfilter = 1
    v2bproof = 1
    v2lproof 1
    comm = 8
