transactions = 4

traceback_limit = 4

#db logging echo(False, True) default: False
db_echo=false

#v2b max replay exchange count(state = faild)
v2b_maxtimes = 99

[btc_conn]
    user = "btc"
    password = "btc"
    host = "127.0.0.1"
    port = 8066
    domain = "violaslayer"
    server = "violaslayer"

[[violas_nodes]]
    host = "52.27.228.84"
    port = 50001
    name = "violas 1"
    faucet = "mint_test.key"

[[violas_nodes]]
    host = "13.68.141.242"
    port = 50001
    name = "violas 2"
    faucet = "mint_test.key"

[[violas_nodes]]
    host = "47.52.195.50"
    port = 50001
    name = "violas 3"
    faucet = "mint_test.key"

[[violas_nodes]]
    host = "18.220.66.235"
    port = 50001
    name = "violas 4"
    faucet = "mint_test.key"

[[libra_nodes]]
    host = "http://client.testnet.libra.org"
    name = "libra"

[[violas_servers]]
    host = "52.27.228.84"
    port = 4000
    user = "violas"
    password = "violas"

[[db_list]]
    host = "127.0.0.1"
    port = 6378
    db = "lfilter"
    password = "violas"
    step = 500

[[db_list]]
    host = "127.0.0.1"
    port = 6378
    db = "vfilter"
    password = "violas"
    step = 1

[[db_list]]
    host = "127.0.0.1"
    port = 6378
    db = "bfilter"
    password = "violas"
    step = 500

#b2v/v2b proof db
[[db_list]]
    host = "127.0.0.1"
    port = 6378
    db = "v2b"
    password = "violas"
    step = 500

[[db_list]]
    host = "127.0.0.1"
    port = 6378
    db = "b2v"
    password = "violas"
    step = 500

#l2vxxx proof db
[[db_list]]
    host = "127.0.0.1"
    port = 6378
    db = "l2vusd"
    password = "violas"
    step = 500

[[db_list]]
    host = "127.0.0.1"
    port = 6378
    db = "l2veur"
    password = "violas"
    step = 500

[[db_list]]
    host = "127.0.0.1"
    port = 6378
    db = "l2vsgd"
    password = "violas"
    step = 500

[[db_list]]
    host = "127.0.0.1"
    port = 6378
    db = "l2vgbp"
    password = "violas"
    step = 500

#v2lxxx proof db
[[db_list]]
    host = "127.0.0.1"
    port = 6378
    db = "v2lusd"
    password = "violas"
    step = 500

[[db_list]]
    host = "127.0.0.1"
    port = 6378
    db = "v2leur"
    password = "violas"
    step = 500

[[db_list]]
    host = "127.0.0.1"
    port = 6378
    db = "v2lsgd"
    password = "violas"
    step = 500

[[db_list]]
    host = "127.0.0.1"
    port = 6378
    db = "v2lgbp"
    password = "violas"
    step = 500

[[db_list]]
    host = "127.0.0.1"
    port = 6378
    db = "record"
    password = "violas"
    step = 500

#violas <-> libra token map
#violas coin:VLSAAA map to libra coin:BBB:  VLSAAA(violas chain) -uniswap-> LBRBBB(violas chain) -map-> BBB(libra chain)
#libra coin map:AAA to violas coin:VLSBBB:  AAA(libra chain) -map-> LBRAAA(violas chain) -uniswap-> VLSBBB(violas chain)
#btc map violas coin: 
#violas btcbtc coin map btc coin:
[token_map]
    Coin1 = "LBRUSD"
    Coin2 = "LBREUR"

#opt type -> target token
[type_token_map]
    v2lusd = "Coin1"
    v2leur = "Coin2"
    l2vusd = "VLSUSD"
    l2veur = "VLSEUR"
    l2vsgd = "VLSSGD"
    l2vgbp = "VLSGBP"

[support_token_id]
    libra=["Coin1", "Coin2"]
    violas = ["VLSUSD", "VLSEUR", "VLSSGD", "VLSGBP", "LBRUSD", "LBREUR", "LBRGBP", "LBRSGD"]

[address_list]
    #receiver addresses
    ##violas chain receiver address
    [[address_list.receiver]]
        address = "4f93ec275410e8be891ff0fd5da41c43aee27591e222fb466654b4f983d8adbb"
        type = "v2b"
        chain = "violas"

    [[address_list.receiver]]
        address = "7cd40d7664d5523d360e8a1e0e2682a2dc49a7c8979f83cde4bc229fb35fd27f"
        type = "v2lusd"
        chain = "violas"
    
    [[address_list.receiver]]
        address = "a239632a99a92e38eeade27b5e3023e22ab774f228b719991463adf0515688a9"
        type = "v2leur"
        chain = "violas"

    ##btc chain receiver address
    [[address_list.receiver]]
        address = "2MyMHV6e4wA2ucV8fFKzXSEFCwrUGr2HEmY"
        type = "b2v"
        chain = "btc"
    
    ##libra chain receiver address
    [[address_list.receiver]]
        address = "da4250b95f4d7f82d9f95ac45ea084b3c5e53097c9f82f81513d02eeb515ecce"
        type = "l2vusd"
        chain = "libra"

    [[address_list.receiver]]
        address = "da4250b95f4d7f82d9f95ac45ea084b3c5e53097c9f82f81513d02eeb515ecce"
        type = "l2veur"
        chain = "libra"

    [[address_list.receiver]]
        address = "da4250b95f4d7f82d9f95ac45ea084b3c5e53097c9f82f81513d02eeb515ecce"
        type = "l2vgbp"
        chain = "libra"

    [[address_list.receiver]]
        address = "da4250b95f4d7f82d9f95ac45ea084b3c5e53097c9f82f81513d02eeb515ecce"
        type = "l2vsgd"
        chain = "libra"

    #sender address
    ##send btcbtc
    [[address_list.sender]]
        address = "4f93ec275410e8be891ff0fd5da41c43aee27591e222fb466654b4f983d8adbb"
        type = "b2v"
        chain = "violas"

    ##send btc
    [[address_list.sender]]
        address = "2MyMHV6e4wA2ucV8fFKzXSEFCwrUGr2HEmY"
        type = "v2b"
        chain = "btc"

    [[address_list.sender]]
        address = "2N9fQcit5KB8vJHmBF5Z4DkUUTCgJA8GKb3"
        type = "v2b"
        chain = "btc"

    [[address_list.sender]]
        address = "2MwBFJJn1f5Sg242D3wNUinKUCKS3GzCn7j"
        type = "v2b"
        chain = "btc"

    ##send violas tokens
    [[address_list.sender]]
        address = "ea6649bcbe1377106201f3829902748278a69a80e181f0c4eefff64a589883aa"
        type = "l2vusd"
        chain = "violas"

    [[address_list.sender]]
        address = "15abf1617d7dd113dd86a7c8ba93dc8841e9a2834bd51cbb0d51a18a8bc75ae4"
        type = "l2veur"
        chain = "violas"

    [[address_list.sender]]
        address = "8f713a7908d15e0745cb997761eeb9ec0c1fcbc4b88106c2e00159da6e5d3ad1"
        type = "l2vgbp"
        chain = "violas"

    [[address_list.sender]]
        address = "4a73cfd0365c641341a7a3bc376423480a82179351b8ecb6c5e68ab7b08622de"
        type = "l2vsgd"
        chain = "violas"

    [[address_list.sender]]
        address = "da4250b95f4d7f82d9f95ac45ea084b3c5e53097c9f82f81513d02eeb515ecce"
        type = "v2lusd"
        chain = "libra"

    [[address_list.sender]]
        address = "da4250b95f4d7f82d9f95ac45ea084b3c5e53097c9f82f81513d02eeb515ecce"
        type = "v2leur"
        chain = "libra"

#    #token info moudule <-> token_id: check token_is is valid.
#    [[address_list.token]]
#        address = "0000000000000000000000000000000000000000000000000000000000000000"
#        tokenid = "BTCBTC"
#        tokenname = "BTCBTC"
#        type = "v2b"
#        chain = "violas"
#
#    [[address_list.token]]
#        address = "0000000000000000000000000000000000000000000000000000000000000000"
#        tokenid = "LBRUSD"
#        tokenname = "LBRUSD"
#        type = "v2lusd"
#        chain = "violas"
#
#    [[address_list.token]]
#        address = "0000000000000000000000000000000000000000000000000000000000000000"
#        tokenid = "LBREUR"
#        tokenname = "LBREUR"
#        type = "v2leur"
#        chain = "violas"
#
#    [[address_list.token]]
#        address = "0000000000000000000000000000000000000000000000000000000000000000"
#        tokenid = "LBRSGD"
#        tokenname = "LBRSGD"
#        type = "v2lSGD"
#        chain = "violas"
#
#    [[address_list.token]]
#        address = "0000000000000000000000000000000000000000000000000000000000000000"
#        tokenid = "LBRGBP"
#        tokenname = "LBRGBP"
#        type = "v2lgbp"
#        chain = "violas"
#
    [[address_list.combine]]
        address = "2N9fQcit5KB8vJHmBF5Z4DkUUTCgJA8GKb3"
        type = "b2v"
        chain = "btc"
[looping_sleep]
    v2b = 1
    b2v = 1
    v2l = 1
    l2v = 1
    vfilter = 1
    lfilter = 1
    v2bproof = 1
    v2lproof 1
    comm = 8
