transactions = 4

traceback_limit = 4

#db logging echo(False, True) default: False
db_echo=false

#v2b max replay exchange count(state = faild)
v2b_maxtimes = 99

#syncing proof flag ; default true
syncing_mod = true

[btc_conn]
    user = "btc"
    password = "btc"
    host = "127.0.0.1"
    port = 8066
    domain = "violaslayer"
    server = "violaslayer"

[[ethereum_nodes]]
    host = "51.140.241.96"
    port = 8545
    name = "ethereum 1"

[[violas_nodes]]
    host = "52.27.228.84"
    port = 50001
    name = "violas 1"
    faucet = "mint_test.key"

[[violas_nodes]]
    host = "18.220.66.235"
    port = 50001
    name = "violas 4"
    faucet = "mint_test.key"

[[violas_nodes]]
    host = "13.68.141.242"
    port = 50001
    name = "violas 2"
    faucet = "mint_test.key"

[[violas_nodes]]
    host = "47.52.195.50"
    port = 50001
    name = "violas 3"
    faucet = "mint_test.key"

[[libra_nodes]]
    host = "http://client.testnet.libra.org"
    name = "libra"

[[violas_servers]]
    host = "52.27.228.84"
    port = 4000
    user = "violas"
    password = "violas"

[db_default]
    host = "127.0.0.1"
    port = 6378
    password = "vtest"
    step = 100

[[db_list]]
    db = "lfilter"
    step = 300

[[db_list]]
    db = "vfilter"
    step = 200

[[db_list]]
    db = "bfilter"
    step = 30

[[db_list]]
    db = "record"

#violas <-> libra token map
#violas coin:VLSAAA map to libra coin:BBB:  VLSAAA(violas chain) -uniswap-> LBRBBB(violas chain) -map-> BBB(libra chain)
#libra coin map:AAA to violas coin:VLSBBB:  AAA(libra chain) -map-> LBRAAA(violas chain) -uniswap-> VLSBBB(violas chain)
#btc map violas coin: 
#violas btcbtc coin map btc coin:

#
#type : metadata's type; token is violas/libra token
#stoken : target chain stable token
#mtoken : violas chain map token only from violas chain swap use this field
#mtoken : stoken = 1:1
#support   : type is support #default = true
#run    : execute analysis proof and exchange, default false
[type_opts]
    [type_opts.v2lusd]
        stoken = "Coin1"
        mtoken = "USD"
        support= true  
        run    = true
    [type_opts.v2leur]
        stoken = "Coin2"
        mtoken = "EUR"
        run    = true
    [type_opts.l2vusd]
        stoken = "VLSUSD"
    [type_opts.l2veur]
        stoken = "VLSEUR"
    [type_opts.l2vsgd]
        stoken = "VLSSGD"
    [type_opts.l2vgbp]
        stoken = "VLSGBP"
    [type_opts.b2vusd]
        stoken = "VLSUSD"
    [type_opts.b2veur]
        stoken = "VLSEUR"
    [type_opts.b2vsgd]
        stoken = "VLSSGD"
    [type_opts.b2vgbp]
        stoken = "VLSGBP"
    [type_opts.b2lusd]
        stoken = "Coin1"
        mtoken = "USD"
    [type_opts.b2leur]
        stoken = "Coin2"
        mtoken = "EUR"
    [type_opts.l2b]
        support = false
        stoken = "BTC"
        mtoken = "BTC"
    [type_opts.v2b]
        stoken = "BTC"
        mtoken = "BTC"
    [type_opts.v2bm]
        stoken = "BTC"
        mtoken = "BTC"
        support = true  
        etype  = "map"
    [type_opts.v2lm]
        support= true  
        run    = false
        etype  = "map"
    [type_opts.l2vm]
        support= true  
        run    = false
        etype  = "map"
    [type_opts.b2vm]
        support= true
        run    = false
        etype  = "map"
    [type_opts.v2vswap]
        support= true  
        run    = false

[type_code]
    b2vm    = "0x3000"
    b2vusd  = "0x4000"
    b2veur  = "0x4010"
    b2vsgd  = "0x4020"
    b2vgbp  = "0x4030"

[swap_module]
    #AssocRoot: 0000000000000000000000000a550c18
    #TreasuryCompliance: 0000000000000000000000000b1e55ed
    #address = "10dfbe77f8a09e9dfcb77bb3d44a14fc"
    address = "00000000000000000000000000000001"

[swap_owner]
    address = "00000000000000000000000045584348"

#swap rule:
#  thd chain -> violas chain : x2v--- . ex l2vusd is libra token to swap violas token(usd)
#  violas chain -> thd chain : v2x--- . ex v2lusd is violas token to swap libra token(coin1)
#  l2vusd:
#     case 1: Coin1/Coin2 -> vlsusd  
#             a. libra transaction: send coinX to address_list.receiver.address(type = l2vusd and chain = "libra")
#             b. bs(bvexchange server) get transaction(type = l2vusd and receiver = a.address) info(amount toaddress ex..)
#             c. bs get address(address_list.sender.address(type = l2vusd and chain = "violas"))
#             d. bs mint map-token(name = usd  amount = b.amount)
#             e. bs execute swap to vlsusd and designated address(b.toaddress)
#             f. bs change transaction state to end(libra transaction and use a.address)
#  v2lusd:
#     case 1: vlsusd/vlseur/vlssgd/vlsgbp -> Coin1
#             a. violas transaction: send vlsXXX to address_list.receiver.address(type = v2lusd and chain = "violas")
#             b. bs get transaction(type = v2lusd and receiver = a.address) info(amount toaddress ex..)
#             c. bs get address_list.combine.address(type = v2lusd and chain = "violas") for swap use to receiver usd token
#             d. bs execute swap, if succeed , get c.address token(usd) changed amount.
#             e. libra transaction: send Coin1 to b.toaddress(amount = d.amount)
#             f. bs change transaction state to end(violas transaction and use a.address)
#             g. bs burn c.address's changed token(usd , amount)
#
# note:
#  1. swap server is single thread(one-token -> one-token), so receiver is multi, but traget token only one address, 
#     in this configure, we can work multi thread(every-type has only one thread)
#  2. libra chain has't swap, so can use the same address(testnet mod), maybe transaction will failed(libra support multi thread 
#     for thread???), anyway wo first ignore it for fast work
#  3. combine address must be difference, because we will calaculation swap result with combine address's token changed
#  4. address_list.sender.address(type = X2vXXX and chain = "violas") must be difference, because we will execute mint token to it
#     and execute swap function with this address. 
[address_list]
    #receiver addresses
    ##violas chain receiver address
    [[address_list.receiver]]
        address = "546f9c996dd049e1a9a2e11d0d001c42e69a3adef1ace4d9c1551e5415e71a4c"
        type = "v2b"
        chain = "violas"

    [[address_list.receiver]]
        address = "5b74546f7b9c711d16e52c062ec18520758538184201f8a875af84a1dee2f6b0"
        type = "v2lusd"
        chain = "violas"
    
    [[address_list.receiver]]
        address = "c1b05029d2d40cc82f458c54d1931e195f829dde3dbda58108fe974bae88b6b2"
        type = "v2leur"
        chain = "violas"

    ##btc chain receiver address
    [[address_list.receiver]]
        address = "2NFMbhLACujsHKa45X4P2fZupVrgB268pbo"
        type = "b2v"
        chain = "btc"
    [[address_list.receiver]]
        address = "2NFMbhLACujsHKa45X4P2fZupVrgB268pbo"
        type = "b2vusd"
        chain = "btc"
    [[address_list.receiver]]
        address = "2NFMbhLACujsHKa45X4P2fZupVrgB268pbo"
        type = "b2veur"
        chain = "btc"
    [[address_list.receiver]]
        address = "2NFMbhLACujsHKa45X4P2fZupVrgB268pbo"
        type = "b2vsgd"
        chain = "btc"
    [[address_list.receiver]]
        address = "2NFMbhLACujsHKa45X4P2fZupVrgB268pbo"
        type = "b2vgbp"
        chain = "btc"
    [[address_list.receiver]]
        address = "2NFMbhLACujsHKa45X4P2fZupVrgB268pbo"
        type = "b2lusd"
        chain = "btc"
    [[address_list.receiver]]
        address = "2NFMbhLACujsHKa45X4P2fZupVrgB268pbo"
        type = "b2leur"
        chain = "btc"
    ##libra chain receiver address
    [[address_list.receiver]]
        address = "03c3c533d9dfd8a2461284303e1b6ebad719c365ab2eda7a4338383641de0baa"
        type = "l2vusd"
        chain = "libra"

    [[address_list.receiver]]
        address = "03c3c533d9dfd8a2461284303e1b6ebad719c365ab2eda7a4338383641de0baa"
        type = "l2veur"
        chain = "libra"

    [[address_list.receiver]]
        address = "03c3c533d9dfd8a2461284303e1b6ebad719c365ab2eda7a4338383641de0baa"
        type = "l2vgbp"
        chain = "libra"

    [[address_list.receiver]]
        address = "03c3c533d9dfd8a2461284303e1b6ebad719c365ab2eda7a4338383641de0baa"
        type = "l2vsgd"
        chain = "libra"

    [[address_list.receiver]]
        address = "03c3c533d9dfd8a2461284303e1b6ebad719c365ab2eda7a4338383641de0baa"
        type = "l2vm"
        chain = "libra"

    [[address_list.receiver]]
        address = "52ce3d1249241c55aa8c178a94342d0b2095f0b580506c46247eede8e496a7d7"
        type = "v2lm"
        chain = "violas"

    [[address_list.receiver]]
        address = "2NFMbhLACujsHKa45X4P2fZupVrgB268pbo"
        type = "b2vm"
        chain = "btc"
    [[address_list.receiver]]
        address = "25f494041501aea8e70f47b9745a497b2a86e053a46eef559546051563b0a5a9"
        type = "v2bm"
        chain = "violas"

    #sender address
    ##send btc
    [[address_list.sender]]
        address = "11f2d7cda024f3a93d4610c754ec9d8a832b060da06971ff011fa2e1bcfc2534"
        type = "b2vm"
        chain = "violas"

    ##send btc
    [[address_list.sender]]
        address = "2NFMbhLACujsHKa45X4P2fZupVrgB268pbo"
        type = "v2b"
        chain = "btc"

    [[address_list.sender]]
        address = "2NFMbhLACujsHKa45X4P2fZupVrgB268pbo"
        type = "v2bm"
        chain = "btc"

    [[address_list.sender]]
        address = "2NFMbhLACujsHKa45X4P2fZupVrgB268pbo"
        type = "l2b"
        chain = "btc"
    ##send violas tokens
    [[address_list.sender]]
        address = "5a11f9999b047ce1393f6bf0b52bc9dd95d79e6913766f5e1cade2d03d1e6e64"
        type = "l2vm"
        chain = "violas"

    [[address_list.sender]]
        address = "32343907c5596588225cfb27fcd31f92f84eeacc64156ff33b5cd90891220b8c"
        type = "l2vusd"
        chain = "violas"

    [[address_list.sender]]
        address = "74e000822ed7db7b100e8ff6b353de874a691c98471901ab5d9706899b060faa"
        type = "l2veur"
        chain = "violas"

    [[address_list.sender]]
        address = "b5483359054753cfb1fbcd30ed1c2a35f4996789360e37ef1f4bd12f15f557bf"
        type = "l2vgbp"
        chain = "violas"

    [[address_list.sender]]
        address = "02f03b1677b2de5dc0b9eba5022d8174398a0fdbc181dc9e8f620d5ac9b25049"
        type = "l2vsgd"
        chain = "violas"

    [[address_list.sender]]
        address = "03c3c533d9dfd8a2461284303e1b6ebad719c365ab2eda7a4338383641de0baa"
        type = "v2lm"
        chain = "libra"

    [[address_list.sender]]
        address = "03c3c533d9dfd8a2461284303e1b6ebad719c365ab2eda7a4338383641de0baa"
        type = "v2lusd"
        chain = "libra"

    [[address_list.sender]]
        address = "03c3c533d9dfd8a2461284303e1b6ebad719c365ab2eda7a4338383641de0baa"
        type = "v2leur"
        chain = "libra"

    [[address_list.sender]]
        address = "d6863a9e12e694bf45abb9881601ac60c8284404776a47ba902fdafc50714357"
        type = "b2vusd"
        chain = "violas"

    [[address_list.sender]]
        address = "71ebab95cc4142f063bd7b9a642c35126a6b7b7a79048a81040b1a170bdb4474"
        type = "b2veur"
        chain = "violas"

    [[address_list.sender]]
        address = "3f0f78901721c6f6a8e188bfa76c0368620f2afbb6c85148494c0d49a0905128"
        type = "b2vsgd"
        chain = "violas"

    [[address_list.sender]]
        address = "6c30d8e6c26ada91c04c55d39ebe365daf15977fa582faf220e97e5a7fc5a09d"
        type = "b2vgbp"
        chain = "violas"
    #combine 
    [[address_list.combine]]
        address = "a4437c1668536113b5271c3acebcc355a2676b99a08dee7362d089973ae560ef"
        type = "v2lusd"
        chain = "violas"
    [[address_list.combine]]
        address = "21ec6f0263b849d73052f1c5080474f5821b052cf4f32219bc1a291275bf85c0"
        type = "v2leur"
        chain = "violas"
    [[address_list.combine]]
        address = "2NFMbhLACujsHKa45X4P2fZupVrgB268pbo"
        type = "l2b"
        chain = "btc"
    [[address_list.combine]]
        address = "46b41eaf4d72319530e6950166aff29328ea7df10477d3513ae30889c7a60a90"
        type = "v2b"
        chain = "violas"
    [[address_list.combine]]
        address = "efcdee4e353167acbf14aaeea61153aeda07b4bf5c33d3c2fb4182ee0f7ae526"
        type = "l2b"
        chain = "violas"
    [[address_list.combine]]
        address = "7381d8ca878e2b3a0fb512787fc4ff18d1dc3a292b3d0b2dff730e5dea388525"
        type = "b2lusd"
        chain = "violas"
    [[address_list.combine]]
        address = "a3a7ef90991670cb288c571f5d0250168fda9c540b3f98dff7779a98bcb24e38"
        type = "b2leur"
        chain = "violas"
    [[address_list.combine]]
        address = "2NFMbhLACujsHKa45X4P2fZupVrgB268pbo"
        type = "b2vm"
        chain = "btc"
    [[address_list.combine]]
        address = "2NFMbhLACujsHKa45X4P2fZupVrgB268pbo"
        type = "b2vusd"
        chain = "btc"
    [[address_list.combine]]
        address = "2NFMbhLACujsHKa45X4P2fZupVrgB268pbo"
        type = "b2veur"
        chain = "btc"
    [[address_list.combine]]
        address = "2NFMbhLACujsHKa45X4P2fZupVrgB268pbo"
        type = "b2vsgd"
        chain = "btc"
    [[address_list.combine]]
        address = "2NFMbhLACujsHKa45X4P2fZupVrgB268pbo"
        type = "b2vgbp"
        chain = "btc"
[looping_sleep]
    vfilter = 1
    lfilter = 1
    bfilter = 1
    comm = 8
